// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmKKUN2JkGBmp5MmJYfuCSXZgh4FXl_LQ',
    appId: '1:105227538071:web:00feacbc298985d505a3d2',
    messagingSenderId: '105227538071',
    projectId: 'app-du-lich-1',
    authDomain: 'app-du-lich-1.firebaseapp.com',
    storageBucket: 'app-du-lich-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-oibUdRPSKhzFyW64vmT1f1SmwzUviPg',
    appId: '1:105227538071:android:31486e7eea84cc4a05a3d2',
    messagingSenderId: '105227538071',
    projectId: 'app-du-lich-1',
    storageBucket: 'app-du-lich-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAan5g_iwilPV-oPl44urCE_NlibRvVO3s',
    appId: '1:105227538071:ios:2ae340413b895c7905a3d2',
    messagingSenderId: '105227538071',
    projectId: 'app-du-lich-1',
    storageBucket: 'app-du-lich-1.firebasestorage.app',
    iosBundleId: 'com.example.appDuLich',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAan5g_iwilPV-oPl44urCE_NlibRvVO3s',
    appId: '1:105227538071:ios:2ae340413b895c7905a3d2',
    messagingSenderId: '105227538071',
    projectId: 'app-du-lich-1',
    storageBucket: 'app-du-lich-1.firebasestorage.app',
    iosBundleId: 'com.example.appDuLich',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmKKUN2JkGBmp5MmJYfuCSXZgh4FXl_LQ',
    appId: '1:105227538071:web:89c10320f5465e7b05a3d2',
    messagingSenderId: '105227538071',
    projectId: 'app-du-lich-1',
    authDomain: 'app-du-lich-1.firebaseapp.com',
    storageBucket: 'app-du-lich-1.firebasestorage.app',
  );
}
